// NOTE: Local Storage
export const ACCESS_TOKEN = "ROOF_LUPIN_ACCESS_TOKEN";
export const REFRESH_TOKEN = "ROOF_LUPIN_REFRESH_TOKEN";
export const SOCIAL_TYPE = "ROOF_LUPIN_SOCIAL_TYPE";
export const USER_INFO = "ROOF_LUPIN_USER_INFO";

// NOTE: Session Storage
export const NAVIGATION_BEFORE_URL = "ROOF_LUPIN_NAVIGATION_BEFORE_URL";
export const BEFORE_ACCESS_AUTH_PAGE_URL = "ROOF_LUPIN_BEFORE_ACCESS_AUTH_PAGE_URL";
export const CATEGORY_SORT_MENU = "ROOF_LUPIN_CATEGORY_SORT_MENU";
