// NOTE: Local Storage
export const ACCESS_TOKEN = "ROOF_LUPIN_ACCESS_TOKEN";
export const REFRESH_TOKEN = "ROOF_LUPIN_REFRESH_TOKEN";
export const SOCIAL_TYPE = "ROOF_LUPIN_SOCIAL_TYPE";
export const USER_INFO = "ROOF_LUPIN_USER_INFO";

// NOTE: Session Storage
export const NAVIGATION_BEFORE_URL = "ROOF_LUPIN_NAVIGATION_BEFORE_URL";
export const BEFORE_ACCESS_AUTH_PAGE_URL = "ROOF_LUPIN_BEFORE_ACCESS_AUTH_PAGE_URL";
export const SPACE_SORT_MENU = "ROOF_LUPIN_SPACE_SORT_MENU";

export const RESERVATION_INFO = "ROOF_LUPIN_RESERVATION_INFO";
export const RESERVATION = "ROOF_LUPIN_RESERVATION";
export const RESERVATION_ADDITIONAL_SERVICES = "ROOF_LUPIN_RESERVATION_ADDITIONAL_SERVICES";
export const RESERVATION_TIME = "ROOF_LUPIN_RESERVATION_TIME";
export const RESERVATION_PACKAGE = "ROOF_LUPIN_RESERVATION_PACKAGE";
export const RESERVATION_DEPOSIT_CONFIRM = "ROOF_LUPIN_RESERVATION_DEPOSIT_CONFIRM";
export const RESERVATION_COUPON = "ROOF_LUPIN_RESERVATION_COUPON";
export const PAYMENT_REFUND = "ROOF_LUPIN_PAYMENT_REFUND";

export const PLATFORM = "ROOF_LUPIN_PLATFORM";

export const MAP_CENTER = "ROOF_LUPIN_MAP_CENTER";
export const MAP_ZOOM = "ROOF_LUPIN_MAP_ZOOM";
